DROP DATABASE IF EXISTS BD_GESCOM;

CREATE DATABASE BD_GESCOM;
USE BD_GESCOM;

CREATE TABLE T_STATUS
(
	STA_ID 					INTEGER 						NOT NULL 	AUTO_INCREMENT,
	STA_NOM 				VARCHAR(50) 					NOT NULL,
	PRIMARY KEY (STA_ID)
)ENGINE = InnoDB;

CREATE TABLE T_LOCALISATION
(
	LOC_ID 					INTEGER 						NOT NULL 	AUTO_INCREMENT,
	LOC_NOM 				VARCHAR(50)						NOT NULL,
	PRIMARY KEY (LOC_ID)
)ENGINE = InnoDB;

CREATE TABLE T_IMAGE
(
	IMA_ID 					INTEGER 						NOT NULL	AUTO_INCREMENT,
	IMA_URL 				TEXT 							NOT NULL,
	IMA_INVISIBLE 			BOOL 			DEFAULT FALSE 	NOT NULL,
	IMA_NOTIFIE 			BOOL 			DEFAULT FALSE 	NOT NULL,
	IMA_DATE 				DATETIME 						NOT NULL,
	UTI_ID 					INTEGER(11),
	PRIMARY KEY (IMA_ID)
)ENGINE = InnoDB;

 CREATE TABLE T_ETATCOMMANDE
(
	ETA_ID 					INTEGER 						NOT NULL 	AUTO_INCREMENT,
	ETA_NOM 				VARCHAR(30) 					NOT NULL,
	PRIMARY KEY (ETA_ID)
 )ENGINE = InnoDB;

CREATE TABLE T_PRODUIT
(
	PRO_ID 					INTEGER 						NOT NULL 	AUTO_INCREMENT,
	PRO_NOM 				VARCHAR(50) 					NOT NULL,
	PRO_DESCRIPTION 		TEXT							NOT NULL,
	PRO_PRIX 				FLOAT UNSIGNED					NOT NULL,
	PRO_INVISIBLE 			BOOL 			DEFAULT FALSE 	NOT NULL,
	PRIMARY KEY (PRO_ID)
)ENGINE = InnoDB;

CREATE TABLE T_IMAGEPRODUIT
(
	IMAPRO_ID 				INTEGER 						NOT NULL 	AUTO_INCREMENT,
	IMAPRO_URL 				TEXT 							NOT NULL,
	PRIMARY KEY (IMAPRO_ID)
)ENGINE = InnoDB;

CREATE TABLE T_CATEGORIE
(
	CAT_ID 					INTEGER 						NOT NULL 	AUTO_INCREMENT,
	CAT_NOM 				VARCHAR(30) 					NOT NULL,
	CAT_ID_T_CATEGORIE 		INTEGER(11) 	DEFAULT NULL,
	PRIMARY KEY (CAT_ID)
)ENGINE = InnoDB;

CREATE TABLE TJ_APPARTENIR_PRO_CAT
(
	CAT_ID 					INTEGER(11) 					NOT NULL,
	PRO_ID 					INTEGER(11) 					NOT NULL,
	PRIMARY KEY (CAT_ID,PRO_ID)
)ENGINE = InnoDB;

CREATE TABLE TJ_DECRIRE_PRO_IMAPRO
(
	IMAPRO_ID 				INTEGER(11) 					NOT NULL,
	PRO_ID 					INTEGER(11) 					NOT NULL,
	PRIMARY KEY (IMAPRO_ID,PRO_ID)
)ENGINE = InnoDB;

CREATE TABLE T_MANIFESTATION
(
	MAN_ID 					INTEGER 						NOT NULL 	AUTO_INCREMENT,
	MAN_Titre				VARCHAR(50)						NOT NULL,
	MAN_DESCRIPTION 		TEXT 							NOT NULL,
	MAN_DATE 				DATETIME,
	MAN_RECURRENTE 			BOOL			DEFAULT FALSE 	NOT NULL,
	MAN_PRIX 				FLOAT UNSIGNED,
	MAN_INVISIBLE 			BOOL			DEFAULT FALSE 	NOT NULL,
	MAN_NOTIFIE 			BOOL			DEFAULT FALSE 	NOT NULL,
	IMA_ID 					INTEGER(11),
	LOC_ID 					INTEGER(11) 					NOT NULL,
	PRIMARY KEY (MAN_ID)
)ENGINE = InnoDB;

CREATE TABLE TJ_RASSEMBLER_IMA_MAN
(
	IMA_ID 					INTEGER(11) 					NOT NULL,
	MAN_ID 					INTEGER(11) 					NOT NULL,
	PRIMARY KEY (IMA_ID,MAN_ID)
)ENGINE = InnoDB;

CREATE TABLE T_UTILISATEUR
(
	UTI_ID 					INTEGER							NOT NULL 	AUTO_INCREMENT,
	UTI_NOM 				VARCHAR(30)						NOT NULL,
	UTI_PRENOM 				VARCHAR(30)						NOT NULL,
	UTI_MAIL 				VARCHAR(30)						NOT NULL,
	UTI_MDP 				VARCHAR(100) 					NOT NULL,
	LOC_ID 					INTEGER(11)						NOT NULL,
	STA_ID					INTEGER(11)		DEFAULT 1		NOT NULL,
	PRIMARY KEY (UTI_ID)
)ENGINE = InnoDB;

CREATE TABLE TJ_INSCRIRE_UTI_MAN
(
	MAN_ID 					INTEGER(11) 					NOT NULL,
	UTI_ID 					INTEGER(11) 					NOT NULL,
	PRIMARY KEY (MAN_ID,UTI_ID)
)ENGINE = InnoDB;

CREATE TABLE T_COMMANDE
(
	COMMA_ID 				INTEGER 						NOT NULL 	AUTO_INCREMENT,
	COMMA_DATE 				DATETIME 						NOT NULL,
	UTI_ID 					INTEGER(11) 					NULL,
	ETA_ID 					INTEGER(11) 	DEFAULT 1 		NOT NULL,
	PRIMARY KEY (COMMA_ID)
)ENGINE = InnoDB;

CREATE TABLE TJ_RASSEMBLER_PRO_COMMA
(
	PRO_ID					INTEGER(11) 					NOT NULL,
	COMMA_ID				INTEGER(11) 					NOT NULL,
	RAS_PRO_COMMA_NOMBRE	INTEGER UNSIGNED				NOT NULL,
	PRIMARY KEY (PRO_ID, COMMA_ID)
)ENGINE = InnoDB;

CREATE TABLE TJ_LIKER_IMA_UTI
(
	IMA_ID 					INTEGER(11) 					NOT NULL,
	UTI_ID 					INTEGER(11) 					NOT NULL,
	PRIMARY KEY (IMA_ID,UTI_ID)
)ENGINE = InnoDB;

CREATE TABLE T_COMMENTAIRE
(
	COMME_ID 				INTEGER 						NOT NULL	 AUTO_INCREMENT,
	COMME_CONTENU 			TEXT 							NOT NULL,
	COMME_DATE 				DATETIME 						NOT NULL,
	COMME_INVISIBLE 		BOOL			DEFAULT FALSE 	NOT NULL,
	COMME_NOTIFIE 			BOOL			DEFAULT FALSE 	NOT NULL,
	UTI_ID 					INTEGER(11) 					NOT NULL,
	IMA_ID 					INTEGER(11) 					NOT NULL,
	PRIMARY KEY (COMME_ID)
)ENGINE=InnoDB;

CREATE TABLE TJ_RASSEMBLER_UTI_PRO
(
	PRO_ID 					INTEGER(11) 					NOT NULL,
	UTI_ID 					INTEGER(11) 					NOT NULL,
	RAS_UTI_PRO_NOMBRE 		INTEGER UNSIGNED				NOT NULL,
	PRIMARY KEY (PRO_ID, UTI_ID)
)ENGINE = InnoDB;

CREATE TABLE TJ_LOCALISER_PRO_LOC
(
	PRO_ID 					INTEGER(11)						NOT NULL,
	LOC_ID 					INTEGER(11)						NOT NULL,
	LOC_PRO_LOC_STOCK		INTEGER							NOT NULL,
	PRIMARY KEY (PRO_ID, LOC_ID)
)ENGINE = InnoDB;

ALTER TABLE TJ_LOCALISER_PRO_LOC
ADD CONSTRAINT fk_tj_loc_id_pro 	FOREIGN KEY (PRO_ID)				REFERENCES T_PRODUIT(PRO_ID);

ALTER TABLE TJ_LOCALISER_PRO_LOC
ADD CONSTRAINT fk_tj_loc_id_loc		FOREIGN KEY (LOC_ID)				REFERENCES T_LOCALISATION(LOC_ID);

ALTER TABLE T_CATEGORIE
ADD CONSTRAINT fk_cat_id_cat 		FOREIGN KEY (CAT_ID_T_CATEGORIE) 	REFERENCES T_CATEGORIE(CAT_ID);

ALTER TABLE TJ_APPARTENIR_PRO_CAT
ADD CONSTRAINT fk_tj_app_cat_id 	FOREIGN KEY (CAT_ID) 				REFERENCES T_CATEGORIE(CAT_ID);

ALTER TABLE TJ_APPARTENIR_PRO_CAT
ADD CONSTRAINT fk_tj_app_pro_id 	FOREIGN KEY (PRO_ID) 				REFERENCES T_PRODUIT(PRO_ID);

ALTER TABLE TJ_DECRIRE_PRO_IMAPRO
ADD CONSTRAINT fk_tj_dec_imapro_id 	FOREIGN KEY (IMAPRO_ID) 			REFERENCES T_IMAGEPRODUIT(IMAPRO_ID);

ALTER TABLE TJ_DECRIRE_PRO_IMAPRO
ADD CONSTRAINT fk_tj_dec_pro_id 	FOREIGN KEY (PRO_ID) 				REFERENCES T_PRODUIT(PRO_ID);

ALTER TABLE T_MANIFESTATION
ADD CONSTRAINT fk_man_id_ima 		FOREIGN KEY (IMA_ID) 				REFERENCES T_IMAGE(IMA_ID) ON DELETE CASCADE;

ALTER TABLE T_MANIFESTATION
ADD CONSTRAINT fk_man_id_loc 		FOREIGN KEY (LOC_ID) 				REFERENCES T_LOCALISATION(LOC_ID);

ALTER TABLE TJ_RASSEMBLER_IMA_MAN
ADD CONSTRAINT fk_rass_ima_id 		FOREIGN KEY (IMA_ID) 				REFERENCES T_IMAGE(IMA_ID) ON DELETE CASCADE;

ALTER TABLE TJ_RASSEMBLER_IMA_MAN
ADD CONSTRAINT fk_rass_man_id 		FOREIGN KEY (MAN_ID) 				REFERENCES  T_MANIFESTATION(MAN_ID);

ALTER TABLE T_UTILISATEUR
ADD CONSTRAINT fk_uti_id_loc 		FOREIGN KEY (LOC_ID) 				REFERENCES  T_LOCALISATION(LOC_ID);

ALTER TABLE T_UTILISATEUR
ADD CONSTRAINT fk_uti_id_sta 		FOREIGN KEY (STA_ID) 				REFERENCES  T_STATUS(STA_ID);

ALTER TABLE TJ_INSCRIRE_UTI_MAN
ADD CONSTRAINT fk_inscrire_uti_id 	FOREIGN KEY (UTI_ID) 				REFERENCES T_UTILISATEUR(UTI_ID);

ALTER TABLE TJ_INSCRIRE_UTI_MAN
ADD CONSTRAINT fk_inscrire_man_id 	FOREIGN KEY (MAN_ID) 				REFERENCES T_MANIFESTATION(MAN_ID);

ALTER TABLE T_IMAGE
ADD CONSTRAINT fk_image_uti_id 		FOREIGN KEY (UTI_ID) 				REFERENCES T_UTILISATEUR(UTI_ID);

ALTER TABLE T_COMMANDE
ADD CONSTRAINT fk_commande_uti_id 	FOREIGN KEY (UTI_ID) 				REFERENCES T_UTILISATEUR(UTI_ID) ON DELETE SET NULL;

ALTER TABLE T_COMMANDE
ADD CONSTRAINT fk_commande_eta_id 	FOREIGN KEY (ETA_ID) 				REFERENCES T_ETATCOMMANDE(ETA_ID);

ALTER TABLE TJ_RASSEMBLER_PRO_COMMA
ADD CONSTRAINT fk_rass_pro_id 		FOREIGN KEY (PRO_ID) 				REFERENCES T_PRODUIT(PRO_ID);

ALTER TABLE TJ_RASSEMBLER_PRO_COMMA
ADD CONSTRAINT fk_rass_comma_id 	FOREIGN KEY (COMMA_ID) 				REFERENCES T_COMMANDE(COMMA_ID);

ALTER TABLE TJ_LIKER_IMA_UTI
ADD CONSTRAINT fk_rass_ima_ids 		FOREIGN KEY (IMA_ID) 				REFERENCES  T_IMAGE(IMA_ID);

ALTER TABLE TJ_LIKER_IMA_UTI
ADD CONSTRAINT fk_rass_uti_ids 		FOREIGN KEY (UTI_ID) 				REFERENCES T_UTILISATEUR(UTI_ID);

ALTER TABLE T_COMMENTAIRE
ADD CONSTRAINT fk_commen_uti_id 	FOREIGN KEY (UTI_ID) 				REFERENCES T_UTILISATEUR(UTI_ID);

ALTER TABLE T_COMMENTAIRE
ADD CONSTRAINT fk_comme_ima_id 		FOREIGN KEY (IMA_ID) 				REFERENCES T_IMAGE(IMA_ID);

ALTER TABLE TJ_RASSEMBLER_UTI_PRO
ADD CONSTRAINT fk_rasse_pro_id 		FOREIGN KEY (PRO_ID) 				REFERENCES T_PRODUIT(PRO_ID);

ALTER TABLE  TJ_RASSEMBLER_UTI_PRO
ADD CONSTRAINT fk_rasse_uti_id 		FOREIGN KEY (UTI_ID) 				REFERENCES T_UTILISATEUR(UTI_ID);